### ISSUE TITLE
Create Marvel wireframes with application flow commentary for workshop application

### ISSUE THREAD

**Issue by burrage** [curiouslearning/workshop_pick_one_1#8]
Please read the ["Required Assignment" section](https://docs.google.com/document/d/1feEzu87OGcXmHxxEoTmCSaClKDgEDzZMA5KU1Ofswsg/edit#heading=h.v8u7xqx2vptn) in this document and submit a link in the comments below.

Keeping the goal of your learning literacy assignment in mind, design wireframes using Marvel focused on the following user story and utilizing the acceptance criteria as benchmarks.

**User Story:**
As a workshop participant, 
I want to create Marvel wireframes with application flow commentary, 
So that I can have a blueprint when building my early-literacy game.

**Acceptance Criteria:**
Given that my game will be played on a smart device, 
When a user opens and plays the game, 
Then the orientation will assume a locked horizontal position so wireframes should be horizontally situated.

Given that my game will be played on both Android smartphones and tablets, 
When a user interacts with the game, 
Then the size of objects should be considered in the wireframe to ensure ease of play.

Given that the purpose of the game is to teach and iterate on one skill, 
When a user plays, 
Then only the necessary elements will be included in the wireframe so as to prevent distraction and ensure comprehension.

Given that the workshop participant has read the design readings and submitted a link to their Marvel wireframes with commentary on the interactions and flow of the application,
When I view the Marvel wireframes,
Then I am able to get a sense of how the application will look, how the user will interact with the app and how they will navigate.

**Comment by ericaashley** [comment]
https://marvelapp.com/1hj36b4
